import dbConnect from './mongodb.js';
import Farmer from './models/Farmer.js';
import Buyer from './models/Buyer.js';
import Listing from './models/Listing.js';
import Order from './models/Order.js';
import Course from './models/Course.js';

export async function seedDatabase() {
  await dbConnect();

  const farmerCount = await Farmer.countDocuments();
  if (farmerCount > 0) return false;

  /* ---------- FARMERS ---------- */
  const farmers = await Farmer.insertMany([
    {
      name: 'Ramesh Patil',
      village: 'Shirur',
      district: 'Pune',
      state: 'Maharashtra',
      phone: '9876543210',
      crops: ['Wheat', 'Onion', 'Sugarcane'],
      landSize: 12,
      aadhaar: '****-****-4321',
      password: 'farmer123',
      rating: 4.5,
      totalRatings: 18,
      completedOrders: 24,
      totalEarnings: 345000,
      memberSince: new Date('2023-03-15'),
    },
    {
      name: 'Lakshmi Devi',
      village: 'Mandya',
      district: 'Mandya',
      state: 'Karnataka',
      phone: '9876543211',
      crops: ['Rice', 'Tomato', 'Soybean'],
      landSize: 8,
      aadhaar: '****-****-8765',
      password: 'farmer123',
      rating: 4.8,
      totalRatings: 32,
      completedOrders: 41,
      totalEarnings: 580000,
      memberSince: new Date('2022-07-20'),
    },
    {
      name: 'Suresh Yadav',
      village: 'Deoria',
      district: 'Deoria',
      state: 'Uttar Pradesh',
      phone: '9876543212',
      crops: ['Wheat', 'Rice', 'Sugarcane'],
      landSize: 15,
      aadhaar: '****-****-2468',
      password: 'farmer123',
      rating: 4.2,
      totalRatings: 12,
      completedOrders: 15,
      totalEarnings: 210000,
      memberSince: new Date('2023-11-01'),
    },
  ]);

  /* ---------- BUYERS ---------- */
  const buyers = await Buyer.insertMany([
    {
      businessName: 'Fresh Basket Retail',
      ownerName: 'Ankit Sharma',
      phone: '9988776655',
      email: 'ankit@freshbasket.in',
      businessType: 'Retailer',
      gstin: '27AABCF1234E1Z5',
      city: 'Mumbai',
      state: 'Maharashtra',
      password: 'buyer123',
      rating: 4.3,
      totalRatings: 15,
      completedOrders: 20,
      totalSpent: 420000,
      memberSince: new Date('2023-01-10'),
    },
    {
      businessName: 'Deccan Wholesale Traders',
      ownerName: 'Priya Kulkarni',
      phone: '9988776656',
      email: 'priya@deccantraders.com',
      businessType: 'Wholesaler',
      gstin: '29BBDEF5678G2Z3',
      city: 'Pune',
      state: 'Maharashtra',
      password: 'buyer123',
      rating: 4.6,
      totalRatings: 28,
      completedOrders: 35,
      totalSpent: 890000,
      memberSince: new Date('2022-05-22'),
    },
  ]);

  /* ---------- LISTINGS ---------- */
  const listings = await Listing.insertMany([
    {
      farmerId: farmers[0]._id,
      farmerName: 'Ramesh Patil',
      farmerDistrict: 'Pune',
      farmerState: 'Maharashtra',
      crop: 'Wheat',
      variety: 'Sharbati',
      quantity: 50,
      unit: 'quintal',
      price: 2200,
      grade: 'A',
      harvestDate: new Date('2024-03-20'),
      description: 'Fresh Sharbati wheat, straight from the field. No pesticides used in last 2 months before harvest.',
      status: 'active',
      bids: [],
    },
    {
      farmerId: farmers[0]._id,
      farmerName: 'Ramesh Patil',
      farmerDistrict: 'Pune',
      farmerState: 'Maharashtra',
      crop: 'Onion',
      variety: 'Nashik Red',
      quantity: 30,
      unit: 'quintal',
      price: 1800,
      grade: 'A',
      harvestDate: new Date('2024-03-25'),
      description: 'Nashik Red onions. Big size, firm. Stored in well-ventilated shed.',
      status: 'bid_received',
      bids: [
        {
          buyerId: buyers[0]._id,
          buyerName: 'Fresh Basket Retail',
          offeredPrice: 1650,
          quantity: 20,
          message: 'We need 20 quintals for our Mumbai stores. Can you deliver by next week?',
          status: 'pending',
        },
      ],
    },
    {
      farmerId: farmers[1]._id,
      farmerName: 'Lakshmi Devi',
      farmerDistrict: 'Mandya',
      farmerState: 'Karnataka',
      crop: 'Rice',
      variety: 'Sona Masuri',
      quantity: 80,
      unit: 'quintal',
      price: 3200,
      grade: 'A',
      harvestDate: new Date('2024-03-10'),
      description: 'Premium Sona Masuri rice. Well sorted, no broken grains. Sun-dried for 3 days.',
      status: 'active',
      bids: [],
    },
    {
      farmerId: farmers[1]._id,
      farmerName: 'Lakshmi Devi',
      farmerDistrict: 'Mandya',
      farmerState: 'Karnataka',
      crop: 'Tomato',
      variety: 'Hybrid',
      quantity: 15,
      unit: 'quintal',
      price: 1400,
      grade: 'B',
      harvestDate: new Date('2024-03-28'),
      description: 'Fresh tomatoes, medium size. Picked this morning. Will stay firm for 5-6 days.',
      status: 'active',
      bids: [],
    },
    {
      farmerId: farmers[2]._id,
      farmerName: 'Suresh Yadav',
      farmerDistrict: 'Deoria',
      farmerState: 'Uttar Pradesh',
      crop: 'Sugarcane',
      variety: 'Co-0238',
      quantity: 200,
      unit: 'quintal',
      price: 350,
      grade: 'A',
      harvestDate: new Date('2024-03-15'),
      description: 'High sucrose content sugarcane, ideal for jaggery making. Fresh cut.',
      status: 'active',
      bids: [],
    },
    {
      farmerId: farmers[2]._id,
      farmerName: 'Suresh Yadav',
      farmerDistrict: 'Deoria',
      farmerState: 'Uttar Pradesh',
      crop: 'Wheat',
      variety: 'HD-2967',
      quantity: 40,
      unit: 'quintal',
      price: 2100,
      grade: 'B',
      harvestDate: new Date('2024-03-18'),
      description: 'Good quality wheat from the Indo-Gangetic plain. Moisture content below 12%.',
      status: 'sold',
      bids: [],
    },
  ]);

  /* ---------- ORDERS ---------- */
  await Order.insertMany([
    {
      listingId: listings[5]._id,
      farmerId: farmers[2]._id,
      buyerId: buyers[1]._id,
      farmerName: 'Suresh Yadav',
      buyerName: 'Deccan Wholesale Traders',
      crop: 'Wheat',
      quantity: 40,
      agreedPrice: 2050,
      status: 'completed',
      paymentStatus: 'paid',
      batchId: 'DEO-2024-7842',
      supplyChainSteps: [
        { label: 'Harvested', status: 'complete', timestamp: new Date('2024-03-18') },
        { label: 'Quality Checked', status: 'complete', timestamp: new Date('2024-03-19') },
        { label: 'Packed & Loaded', status: 'complete', timestamp: new Date('2024-03-20') },
        { label: 'In Transit', status: 'complete', timestamp: new Date('2024-03-21') },
        { label: 'Delivered', status: 'complete', timestamp: new Date('2024-03-22') },
      ],
    },
    {
      listingId: listings[0]._id,
      farmerId: farmers[0]._id,
      buyerId: buyers[0]._id,
      farmerName: 'Ramesh Patil',
      buyerName: 'Fresh Basket Retail',
      crop: 'Wheat',
      quantity: 25,
      agreedPrice: 2150,
      status: 'in_progress',
      paymentStatus: 'pending',
      batchId: 'PUN-2024-3156',
      supplyChainSteps: [
        { label: 'Harvested', status: 'complete', timestamp: new Date('2024-03-20') },
        { label: 'Quality Checked', status: 'complete', timestamp: new Date('2024-03-21') },
        { label: 'Packed & Loaded', status: 'active', timestamp: null },
        { label: 'In Transit', status: 'pending', timestamp: null },
        { label: 'Delivered', status: 'pending', timestamp: null },
      ],
    },
  ]);

  /* ---------- COURSES ---------- */
  await Course.insertMany([
    { title: 'Organic Farming Certification', duration: '6 weeks', stipend: '₹500/week', location: 'Pune', type: 'course' },
    { title: 'Cold Storage Operator', duration: '4 weeks', stipend: '₹600/week', location: 'Nashik', type: 'course' },
    { title: 'Agri-Drone Pilot Training', duration: '3 weeks', stipend: '₹800/week', location: 'Aurangabad', type: 'course' },
    { title: 'Soil Testing Technician', duration: '5 weeks', stipend: '₹550/week', location: 'Nagpur', type: 'course' },
    { title: 'Rural Delivery Partner', duration: 'Full-time', salary: '₹12,000/month', location: 'Pan Maharashtra', type: 'job', company: 'AgroLink Logistics', role: 'Delivery Partner' },
    { title: 'Warehouse Assistant', duration: 'Full-time', salary: '₹14,000/month', location: 'Pune', type: 'job', company: 'FreshChain India', role: 'Warehouse Ops' },
    { title: 'Farm Equipment Mechanic', duration: 'Full-time', salary: '₹16,000/month', location: 'Nashik', type: 'job', company: 'KisanTech Solutions', role: 'Field Mechanic' },
  ]);

  return true;
}
